language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "NX0Use1toWL55JrlT+VOamXGhG9tKfmkgVSMBH4qSVSVY/Fgvdqpujr7l/3ejIEpEr7rRPEvAG0ZoC7i5kufE+S+5yJFHrqBqbKRFplqXSVv+Bhnh0rvEaLdinsFAx8QoBaY+Kr6BImv5A/bQTEZtGCAeOUk0zOKsN8NzDHYbzM="

addons:
  coverity_scan:
    project:
      name: "McPringle/sportchef-server"
      description: "Build submitted via Travis CI"
    notification_email: marcus@fihlon.ch
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compileJava compileTestJava"
    branch_pattern: coverity_scan

after_success:
  - ./gradlew jacocoTestReport coveralls
