server:
  rootPath: '/api/*'

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:sportchef-test
  properties:
    charSet: UTF-8
  validationQuery: "/* Health Check */ SELECT 1"
  migrateOnStart: true
  dropAllBeforeMigration: true

logging:
  level: ALL
  appenders:
    - type: console
      threshold: INFO
      target: stdout
    - type: file
      currentLogFilename: ./logs/sportchef-test.log
      archivedLogFilenamePattern: ./logs/sportchef-test-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
